// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIt3AqUvPqGY2zRAcJRnoycI_gHFBPE1w',
    appId: '1:899201708229:web:90c1e47a3d67b6f3e800ac',
    messagingSenderId: '899201708229',
    projectId: 'flutter-chat-app-c09e8',
    authDomain: 'flutter-chat-app-c09e8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c09e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeK6baVgMIU9FlaC9gLGkf-X5G5FM1WY',
    appId: '1:899201708229:android:6aea4e085af6e4e3e800ac',
    messagingSenderId: '899201708229',
    projectId: 'flutter-chat-app-c09e8',
    storageBucket: 'flutter-chat-app-c09e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZutdoHqtz3TNmEJj24YJVZt4v2TPbT0',
    appId: '1:899201708229:ios:ffc31c035d7d2eede800ac',
    messagingSenderId: '899201708229',
    projectId: 'flutter-chat-app-c09e8',
    storageBucket: 'flutter-chat-app-c09e8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZutdoHqtz3TNmEJj24YJVZt4v2TPbT0',
    appId: '1:899201708229:ios:ffc31c035d7d2eede800ac',
    messagingSenderId: '899201708229',
    projectId: 'flutter-chat-app-c09e8',
    storageBucket: 'flutter-chat-app-c09e8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIt3AqUvPqGY2zRAcJRnoycI_gHFBPE1w',
    appId: '1:899201708229:web:7e6c6ecc895ed640e800ac',
    messagingSenderId: '899201708229',
    projectId: 'flutter-chat-app-c09e8',
    authDomain: 'flutter-chat-app-c09e8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c09e8.firebasestorage.app',
  );
}
